name: 'Dispatch Broker Action'
description: 'A GitHub Action to dispatch workflows via the GitHub API using a Python script.'
author: 'Your Name <your.email@example.com>'
inputs:
  token:
    description: 'GitHub token with repo/workflow permissions'
    required: true
  repository:
    description: 'Target repository in the format owner/repo'
    required: true
  ref:
    description: 'Git ref (branch, tag, or SHA) to run the workflow on'
    required: true
    default: 'main'
  exclude_workflows:
    description: 'Comma-separated list of workflow filenames to exclude from dispatching'
    required: true
  client_payload:
    description: 'JSON string to pass as client_payload to the workflow dispatch event'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
      shell: bash

    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Run main.py
      run: main.py --token "${{ inputs.token }}" --repository "${{ inputs.repository }}" --ref "${{ inputs.ref }}" --exclude_workflows "${{ inputs.exclude_workflows }}" --client_payload '${{ inputs.client_payload }}'
      shell: bash
